version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/code
      - ./demo/conf/nginx.conf:/etc/nginx/nginx.conf
  php:
    build: ./demo/build
    volumes:
      - ./:/code
    depends_on:
      - nginx
  mysql:
    image: mysql:8.2
    env_file:
      - .env
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSSWORD=PETITnuage-26
      - MYSQL_DATABASE=symfony_network
      - MYSQL_USER=damien
      - MYSQL_PASSWORD=PETITnuage-26
      - MYSQL_ALLOW_EMPTY_PASSWORD=0
      # - MYSQL_ROOT_PASSSWORD=${MYSQL_ROOT_PASSSWORD}
      # - MYSQL_DATABASE=${MYSQL_DATABASE}
      # - MYSQL_USER=${MYSQL_USER}
      # - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - data:/var/lib/mysql
volumes:
  data: {}
