# version: '3'

# services:
#   nginx:
#     image: nginx:latest
#     ports:
#       - "8080:80"
#     volumes:
#       - ./:/code
#       - ./docker-symfony-demo/conf/nginx.conf:/etc/nginx/nginx.conf
#       - ./docker-symfony-demo/var/log/nginx/access.log:/var/log/nginx/access.log
#       - ./docker-symfony-demo/var/log/nginx/error.log:/var/log/nginx/error.log
#   php:
#     build: ./docker-symfony-demo/build
#     volumes:
#       - ./:/code
#       - ./docker-symfony-demo/conf/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
#       - .root:/var/www/html:ro
#       - ./docker-symfony-demo/conf/php.ini-development:/usr/local/etc/php/php.ini
#       - ./docker-symfony-demo/var/log/php/php.log:/var/log/php/php_errors.log
#     depends_on:
#       - nginx
#   mysql:
#     image: mysql:8.2
#     env_file:
#       - .env
#     ports:
#       - 3306:3306
#     environment:
#       - MYSQL_ROOT_PASSSWORD=PETITnuage-26
#       - MYSQL_DATABASE=symfony_network
#       - MYSQL_USER=damien
#       - MYSQL_PASSWORD=PETITnuage-26
#       - MYSQL_ALLOW_EMPTY_PASSWORD=0
#       # MYSQL_ROOT_PASSSWORD: ${MYSQL_ROOT_PASSSWORD}
#       # MYSQL_DATABASE: ${MYSQL_DATABASE}
#       # MYSQL_USER: ${MYSQL_USER}
#       # MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#     volumes:
#       - data:/var/lib/mysql
#       - ./docker-symfony-demo/conf/my.cnf:/etc/mysql/my.cnf
#       - ./docker-symfony-demo/var/log/mysql/mysql.log:/var/log/mysql/mysql.log
# volumes:
#   data: {}

version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/code
      - ./docker-symfony-demo/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./docker-symfony-demo/var/log/nginx/access.log:/var/log/nginx/access.log
      - ./docker-symfony-demo/var/log/nginx/error.log:/var/log/nginx/error.log

  php:
    build: ./docker-symfony-demo/build
    volumes:
      - ./:/code
      - ./docker-symfony-demo/conf/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
      - .root:/var/www/html:ro
      - ./docker-symfony-demo/conf/php.ini-development:/usr/local/etc/php/php.ini
      - ./docker-symfony-demo/var/log/php/php.log:/var/log/php/php_errors.log
    depends_on:
      - nginx

  mysql:
    image: mysql:8.2
    env_file:
      - .env
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=PETITnuage-26
      - MYSQL_DATABASE=symfony_network
      - MYSQL_USER=damien
      - MYSQL_PASSWORD=PETITnuage-26
      - MYSQL_ALLOW_EMPTY_PASSWORD=0
    volumes:
      - data:/var/lib/mysql
      - ./docker-symfony-demo/conf/my.cnf:/etc/mysql/my.cnf
      - ./docker-symfony-demo/var/log/mysql/mysql.log:/var/log/mysql/mysql.log

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.2
    volumes:
      - ./docker-symfony-demo/conf/logstash.conf:/usr/share/logstash/pipeline/logstash.conf

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.15.2
    volumes:
      - ./docker-symfony-demo/conf/filebeat.yml:/usr/share/filebeat/filebeat.yml

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    ports:
      - "5601:5601"
    volumes:
      - kibana_data:/usr/share/kibana/data
    depends_on:
      - elasticsearch

volumes:
  data:
  elasticsearch_data:
  kibana_data:
