version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/code
      - ./docker-symfony-demo/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./docker-symfony-demo/var/log/nginx/access.log:/var/log/nginx/access.log
      - ./docker-symfony-demo/var/log/nginx/error.log:/var/log/nginx/error.log

  php:
    build: ./docker-symfony-demo/build
    volumes:
      - ./:/code
      - ./docker-symfony-demo/conf/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
      - .root:/var/www/html:ro
      - ./docker-symfony-demo/conf/php.ini-development:/usr/local/etc/php/php.ini
      - ./docker-symfony-demo/var/log/php/error.log:/var/log/php/php_errors.log
    depends_on:
      - nginx

  mysql:
    image: mysql:8.2
    env_file:
      - .env
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=PETITnuage-26
      - MYSQL_DATABASE=symfony_network
      - MYSQL_USER=damien
      - MYSQL_PASSWORD=PETITnuage-26
      - MYSQL_ALLOW_EMPTY_PASSWORD=0
    volumes:
      - data:/var/lib/mysql
      - ./docker-symfony-demo/conf/my.cnf:/etc/mysql/my.cnf
      - ./docker-symfony-demo/var/log/mysql:/var/log/mysql  
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
 
#   # SERVICE DE ELASTICSEARCH
#   elasticsearch:
#     image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
#     environment:
#       - discovery.type=single-node
#     ports:
#       - "9200:9200"
 
#   # SERVICE DE LOGSTASH
#   logstash:
#     image: docker.elastic.co/logstash/logstash:7.15.2
#     volumes:
#       - ./docker-symfony-demo/conf/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
#     ports:
#       - "5001:5001"
#     depends_on:
#       - elasticsearch
 
#   # SERVICE DE KIBANA
#   kibana:
#     image: docker.elastic.co/kibana/kibana:7.15.2
#     ports:
#       - "5601:5601"
#     depends_on:
#       - elasticsearch
 
#   # SERVICE DE FILEBEAT
#   filebeat:
#     image: docker.elastic.co/beats/filebeat:7.15.2
#     volumes:
#       - ./docker-symfony-demo/conf/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
#       - ./docker-symfony-demo/var/log/filebeat:/logs:ro
#     depends_on:
#       - logstash
#     user: root
#     cap_add:
#       - ALL
 
# volumes:
#   data: {}

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elk_network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.2
    container_name: logstash
    volumes:
      - ./docker-symfony-demo/conf/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - logstash-data:/usr/share/logstash/data
    networks:
      - elk_network

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.10.2
    container_name: filebeat
    volumes:
      - ./docker-symfony-demo/conf/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/log:/var/log
    networks:
      - elk_network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - elk_network

networks:
  elk_network:

volumes:
  data:
  elasticsearch-data:
  logstash-data:
